// Curated emoji dataset for the in-app picker.
// Each entry: [emoji, name]. Name is lowercased keywords used for search.

export interface EmojiEntry {
  e: string;
  n: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  items: EmojiEntry[];
}

const smileys: EmojiEntry[] = [
  { e: '😀', n: 'grinning face' },
  { e: '😃', n: 'grinning face big eyes' },
  { e: '😄', n: 'grinning face smiling eyes' },
  { e: '😁', n: 'beaming face' },
  { e: '😆', n: 'grinning squinting laugh' },
  { e: '😅', n: 'grinning sweat' },
  { e: '🤣', n: 'rolling on floor laughing rofl' },
  { e: '😂', n: 'face tears joy lol' },
  { e: '🙂', n: 'slightly smiling face' },
  { e: '🙃', n: 'upside down face' },
  { e: '🫠', n: 'melting face' },
  { e: '😉', n: 'winking face' },
  { e: '😊', n: 'smiling face smiling eyes blush' },
  { e: '😇', n: 'smiling face halo angel' },
  { e: '🥰', n: 'smiling face hearts love' },
  { e: '😍', n: 'smiling face heart eyes' },
  { e: '🤩', n: 'star struck eyes' },
  { e: '😘', n: 'face blowing kiss' },
  { e: '😗', n: 'kissing face' },
  { e: '☺️', n: 'smiling face' },
  { e: '😚', n: 'kissing face closed eyes' },
  { e: '😙', n: 'kissing face smiling eyes' },
  { e: '🥲', n: 'smiling face tear' },
  { e: '😋', n: 'face savoring food yum' },
  { e: '😛', n: 'face tongue' },
  { e: '😜', n: 'winking face tongue' },
  { e: '🤪', n: 'zany face crazy' },
  { e: '😝', n: 'squinting face tongue' },
  { e: '🤑', n: 'money mouth face' },
  { e: '🤗', n: 'hugging face' },
  { e: '🤭', n: 'face hand over mouth' },
  { e: '🫢', n: 'face open eyes hand mouth' },
  { e: '🫣', n: 'face peeking through hand' },
  { e: '🤫', n: 'shushing face shh' },
  { e: '🤔', n: 'thinking face' },
  { e: '🫡', n: 'saluting face' },
  { e: '🤐', n: 'zipper mouth face' },
  { e: '🤨', n: 'face raised eyebrow skeptical' },
  { e: '😐', n: 'neutral face' },
  { e: '😑', n: 'expressionless face' },
  { e: '😶', n: 'face without mouth' },
  { e: '🫥', n: 'dotted line face' },
  { e: '😶‍🌫️', n: 'face in clouds' },
  { e: '😏', n: 'smirking face' },
  { e: '😒', n: 'unamused face' },
  { e: '🙄', n: 'face rolling eyes' },
  { e: '😬', n: 'grimacing face' },
  { e: '😮‍💨', n: 'face exhaling' },
  { e: '🤥', n: 'lying face' },
  { e: '😌', n: 'relieved face' },
  { e: '😔', n: 'pensive face' },
  { e: '😪', n: 'sleepy face' },
  { e: '🤤', n: 'drooling face' },
  { e: '😴', n: 'sleeping face zzz' },
  { e: '😷', n: 'face medical mask sick' },
  { e: '🤒', n: 'face thermometer sick' },
  { e: '🤕', n: 'face head bandage hurt' },
  { e: '🤢', n: 'nauseated face sick' },
  { e: '🤮', n: 'face vomiting puke' },
  { e: '🤧', n: 'sneezing face' },
  { e: '🥵', n: 'hot face heat' },
  { e: '🥶', n: 'cold face freezing' },
  { e: '🥴', n: 'woozy face drunk' },
  { e: '😵', n: 'face crossed out eyes dizzy' },
  { e: '😵‍💫', n: 'face spiral eyes' },
  { e: '🤯', n: 'exploding head mind blown' },
  { e: '🤠', n: 'cowboy hat face' },
  { e: '🥳', n: 'partying face party' },
  { e: '🥸', n: 'disguised face' },
  { e: '😎', n: 'smiling face sunglasses cool' },
  { e: '🤓', n: 'nerd face' },
  { e: '🧐', n: 'face monocle' },
  { e: '😕', n: 'confused face' },
  { e: '🫤', n: 'face diagonal mouth' },
  { e: '😟', n: 'worried face' },
  { e: '🙁', n: 'slightly frowning face' },
  { e: '☹️', n: 'frowning face' },
  { e: '😮', n: 'face open mouth' },
  { e: '😯', n: 'hushed face' },
  { e: '😲', n: 'astonished face' },
  { e: '😳', n: 'flushed face' },
  { e: '🥺', n: 'pleading face' },
  { e: '🥹', n: 'face holding back tears' },
  { e: '😦', n: 'frowning face open mouth' },
  { e: '😧', n: 'anguished face' },
  { e: '😨', n: 'fearful face scared' },
  { e: '😰', n: 'anxious face sweat' },
  { e: '😥', n: 'sad relieved face' },
  { e: '😢', n: 'crying face tear' },
  { e: '😭', n: 'loudly crying face sob' },
  { e: '😱', n: 'face screaming fear' },
  { e: '😖', n: 'confounded face' },
  { e: '😣', n: 'persevering face' },
  { e: '😞', n: 'disappointed face' },
  { e: '😓', n: 'downcast face sweat' },
  { e: '😩', n: 'weary face' },
  { e: '😫', n: 'tired face' },
  { e: '🥱', n: 'yawning face' },
  { e: '😤', n: 'face steam from nose' },
  { e: '😡', n: 'enraged face angry' },
  { e: '😠', n: 'angry face' },
  { e: '🤬', n: 'face symbols mouth swearing' },
  { e: '😈', n: 'smiling face horns devil' },
  { e: '👿', n: 'angry face horns imp' },
  { e: '💀', n: 'skull dead' },
  { e: '☠️', n: 'skull crossbones' },
  { e: '💩', n: 'pile of poo' },
  { e: '🤡', n: 'clown face' },
  { e: '👹', n: 'ogre' },
  { e: '👺', n: 'goblin' },
  { e: '👻', n: 'ghost' },
  { e: '👽', n: 'alien' },
  { e: '👾', n: 'alien monster' },
  { e: '🤖', n: 'robot' },
  { e: '😺', n: 'grinning cat' },
  { e: '😸', n: 'grinning cat smiling eyes' },
  { e: '😹', n: 'cat tears joy' },
  { e: '😻', n: 'smiling cat heart eyes' },
  { e: '😼', n: 'cat wry smile' },
  { e: '😽', n: 'kissing cat' },
  { e: '🙀', n: 'weary cat' },
  { e: '😿', n: 'crying cat' },
  { e: '😾', n: 'pouting cat' },
];

const gestures: EmojiEntry[] = [
  { e: '👋', n: 'waving hand hello hi' },
  { e: '🤚', n: 'raised back of hand' },
  { e: '🖐️', n: 'hand fingers splayed' },
  { e: '✋', n: 'raised hand stop' },
  { e: '🖖', n: 'vulcan salute' },
  { e: '🫱', n: 'rightwards hand' },
  { e: '🫲', n: 'leftwards hand' },
  { e: '🫳', n: 'palm down hand' },
  { e: '🫴', n: 'palm up hand' },
  { e: '👌', n: 'ok hand' },
  { e: '🤌', n: 'pinched fingers' },
  { e: '🤏', n: 'pinching hand' },
  { e: '✌️', n: 'victory hand peace' },
  { e: '🤞', n: 'crossed fingers luck' },
  { e: '🫰', n: 'hand index thumb crossed' },
  { e: '🤟', n: 'love you gesture' },
  { e: '🤘', n: 'sign of horns rock' },
  { e: '🤙', n: 'call me hand shaka' },
  { e: '👈', n: 'backhand index pointing left' },
  { e: '👉', n: 'backhand index pointing right' },
  { e: '👆', n: 'backhand index pointing up' },
  { e: '🖕', n: 'middle finger' },
  { e: '👇', n: 'backhand index pointing down' },
  { e: '☝️', n: 'index pointing up' },
  { e: '🫵', n: 'index pointing at viewer' },
  { e: '👍', n: 'thumbs up like' },
  { e: '👎', n: 'thumbs down dislike' },
  { e: '✊', n: 'raised fist' },
  { e: '👊', n: 'oncoming fist bump' },
  { e: '🤛', n: 'left facing fist' },
  { e: '🤜', n: 'right facing fist' },
  { e: '👏', n: 'clapping hands' },
  { e: '🙌', n: 'raising hands praise' },
  { e: '🫶', n: 'heart hands' },
  { e: '👐', n: 'open hands' },
  { e: '🤲', n: 'palms up together' },
  { e: '🤝', n: 'handshake' },
  { e: '🙏', n: 'folded hands please thanks pray' },
  { e: '✍️', n: 'writing hand' },
  { e: '💅', n: 'nail polish' },
  { e: '🤳', n: 'selfie' },
  { e: '💪', n: 'flexed biceps strong' },
  { e: '🦾', n: 'mechanical arm' },
  { e: '🦿', n: 'mechanical leg' },
  { e: '🦵', n: 'leg' },
  { e: '🦶', n: 'foot' },
  { e: '👂', n: 'ear' },
  { e: '👃', n: 'nose' },
  { e: '🧠', n: 'brain' },
  { e: '🫀', n: 'anatomical heart' },
  { e: '🫁', n: 'lungs' },
  { e: '🦷', n: 'tooth' },
  { e: '🦴', n: 'bone' },
  { e: '👀', n: 'eyes look' },
  { e: '👁️', n: 'eye' },
  { e: '👅', n: 'tongue' },
  { e: '👄', n: 'mouth' },
];

const hearts: EmojiEntry[] = [
  { e: '❤️', n: 'red heart love' },
  { e: '🧡', n: 'orange heart' },
  { e: '💛', n: 'yellow heart' },
  { e: '💚', n: 'green heart' },
  { e: '💙', n: 'blue heart' },
  { e: '💜', n: 'purple heart' },
  { e: '🖤', n: 'black heart' },
  { e: '🤍', n: 'white heart' },
  { e: '🤎', n: 'brown heart' },
  { e: '💔', n: 'broken heart' },
  { e: '❤️‍🔥', n: 'heart on fire' },
  { e: '❤️‍🩹', n: 'mending heart' },
  { e: '💖', n: 'sparkling heart' },
  { e: '💗', n: 'growing heart' },
  { e: '💓', n: 'beating heart' },
  { e: '💞', n: 'revolving hearts' },
  { e: '💕', n: 'two hearts' },
  { e: '💟', n: 'heart decoration' },
  { e: '❣️', n: 'heart exclamation' },
  { e: '💌', n: 'love letter' },
  { e: '💋', n: 'kiss mark' },
  { e: '💯', n: 'hundred points 100' },
  { e: '💢', n: 'anger symbol' },
  { e: '💥', n: 'collision boom' },
  { e: '💫', n: 'dizzy star' },
  { e: '💦', n: 'sweat droplets' },
  { e: '💨', n: 'dashing away wind' },
  { e: '🕳️', n: 'hole' },
  { e: '💣', n: 'bomb' },
  { e: '💬', n: 'speech balloon' },
  { e: '🗨️', n: 'left speech bubble' },
  { e: '🗯️', n: 'right anger bubble' },
  { e: '💭', n: 'thought balloon' },
  { e: '💤', n: 'zzz sleep' },
];

const animals: EmojiEntry[] = [
  { e: '🐶', n: 'dog face' },
  { e: '🐱', n: 'cat face' },
  { e: '🐭', n: 'mouse face' },
  { e: '🐹', n: 'hamster' },
  { e: '🐰', n: 'rabbit face' },
  { e: '🦊', n: 'fox' },
  { e: '🐻', n: 'bear' },
  { e: '🐼', n: 'panda' },
  { e: '🐻‍❄️', n: 'polar bear' },
  { e: '🐨', n: 'koala' },
  { e: '🐯', n: 'tiger face' },
  { e: '🦁', n: 'lion' },
  { e: '🐮', n: 'cow face' },
  { e: '🐷', n: 'pig face' },
  { e: '🐸', n: 'frog' },
  { e: '🐵', n: 'monkey face' },
  { e: '🙈', n: 'see no evil monkey' },
  { e: '🙉', n: 'hear no evil monkey' },
  { e: '🙊', n: 'speak no evil monkey' },
  { e: '🐒', n: 'monkey' },
  { e: '🐔', n: 'chicken' },
  { e: '🐧', n: 'penguin' },
  { e: '🐦', n: 'bird' },
  { e: '🐤', n: 'baby chick' },
  { e: '🦆', n: 'duck' },
  { e: '🦅', n: 'eagle' },
  { e: '🦉', n: 'owl' },
  { e: '🦇', n: 'bat' },
  { e: '🐺', n: 'wolf' },
  { e: '🐗', n: 'boar' },
  { e: '🐴', n: 'horse face' },
  { e: '🦄', n: 'unicorn' },
  { e: '🐝', n: 'honeybee' },
  { e: '🪱', n: 'worm' },
  { e: '🐛', n: 'bug' },
  { e: '🦋', n: 'butterfly' },
  { e: '🐌', n: 'snail' },
  { e: '🐞', n: 'lady beetle' },
  { e: '🐜', n: 'ant' },
  { e: '🪰', n: 'fly' },
  { e: '🪲', n: 'beetle' },
  { e: '🦂', n: 'scorpion' },
  { e: '🐢', n: 'turtle' },
  { e: '🐍', n: 'snake' },
  { e: '🦎', n: 'lizard' },
  { e: '🦖', n: 't rex dinosaur' },
  { e: '🦕', n: 'sauropod' },
  { e: '🐙', n: 'octopus' },
  { e: '🦑', n: 'squid' },
  { e: '🦐', n: 'shrimp' },
  { e: '🦞', n: 'lobster' },
  { e: '🦀', n: 'crab' },
  { e: '🐡', n: 'blowfish' },
  { e: '🐠', n: 'tropical fish' },
  { e: '🐟', n: 'fish' },
  { e: '🐬', n: 'dolphin' },
  { e: '🐳', n: 'spouting whale' },
  { e: '🐋', n: 'whale' },
  { e: '🦈', n: 'shark' },
  { e: '🐊', n: 'crocodile' },
  { e: '🐅', n: 'tiger' },
  { e: '🐆', n: 'leopard' },
  { e: '🦓', n: 'zebra' },
  { e: '🦍', n: 'gorilla' },
  { e: '🦧', n: 'orangutan' },
  { e: '🐘', n: 'elephant' },
  { e: '🦣', n: 'mammoth' },
  { e: '🦛', n: 'hippopotamus' },
  { e: '🦏', n: 'rhinoceros' },
  { e: '🐪', n: 'camel' },
  { e: '🦒', n: 'giraffe' },
  { e: '🦘', n: 'kangaroo' },
  { e: '🦬', n: 'bison' },
  { e: '🐂', n: 'ox' },
  { e: '🐄', n: 'cow' },
  { e: '🐎', n: 'horse' },
  { e: '🐖', n: 'pig' },
  { e: '🐏', n: 'ram' },
  { e: '🐑', n: 'ewe sheep' },
  { e: '🦙', n: 'llama' },
  { e: '🐐', n: 'goat' },
  { e: '🦌', n: 'deer' },
  { e: '🐕', n: 'dog' },
  { e: '🐩', n: 'poodle' },
  { e: '🦮', n: 'guide dog' },
  { e: '🐕‍🦺', n: 'service dog' },
  { e: '🐈', n: 'cat' },
  { e: '🐈‍⬛', n: 'black cat' },
  { e: '🐓', n: 'rooster' },
  { e: '🦃', n: 'turkey' },
  { e: '🦚', n: 'peacock' },
  { e: '🦜', n: 'parrot' },
  { e: '🦢', n: 'swan' },
  { e: '🦩', n: 'flamingo' },
  { e: '🕊️', n: 'dove peace' },
  { e: '🌸', n: 'cherry blossom' },
  { e: '🌷', n: 'tulip' },
  { e: '🌹', n: 'rose' },
  { e: '🥀', n: 'wilted flower' },
  { e: '🌺', n: 'hibiscus' },
  { e: '🌻', n: 'sunflower' },
  { e: '🌼', n: 'blossom' },
  { e: '🌱', n: 'seedling' },
  { e: '🌲', n: 'evergreen tree' },
  { e: '🌳', n: 'deciduous tree' },
  { e: '🌴', n: 'palm tree' },
  { e: '🌵', n: 'cactus' },
  { e: '🌾', n: 'sheaf of rice' },
  { e: '🌿', n: 'herb' },
  { e: '☘️', n: 'shamrock' },
  { e: '🍀', n: 'four leaf clover' },
  { e: '🍁', n: 'maple leaf' },
  { e: '🍂', n: 'fallen leaf' },
  { e: '🍃', n: 'leaf fluttering' },
];

const food: EmojiEntry[] = [
  { e: '🍎', n: 'red apple' },
  { e: '🍏', n: 'green apple' },
  { e: '🍊', n: 'tangerine orange' },
  { e: '🍋', n: 'lemon' },
  { e: '🍌', n: 'banana' },
  { e: '🍉', n: 'watermelon' },
  { e: '🍇', n: 'grapes' },
  { e: '🍓', n: 'strawberry' },
  { e: '🫐', n: 'blueberries' },
  { e: '🍈', n: 'melon' },
  { e: '🍒', n: 'cherries' },
  { e: '🍑', n: 'peach' },
  { e: '🥭', n: 'mango' },
  { e: '🍍', n: 'pineapple' },
  { e: '🥥', n: 'coconut' },
  { e: '🥝', n: 'kiwi fruit' },
  { e: '🍅', n: 'tomato' },
  { e: '🍆', n: 'eggplant' },
  { e: '🥑', n: 'avocado' },
  { e: '🥦', n: 'broccoli' },
  { e: '🥬', n: 'leafy green' },
  { e: '🥒', n: 'cucumber' },
  { e: '🌶️', n: 'hot pepper' },
  { e: '🫑', n: 'bell pepper' },
  { e: '🌽', n: 'ear of corn' },
  { e: '🥕', n: 'carrot' },
  { e: '🫒', n: 'olive' },
  { e: '🧄', n: 'garlic' },
  { e: '🧅', n: 'onion' },
  { e: '🥔', n: 'potato' },
  { e: '🍠', n: 'roasted sweet potato' },
  { e: '🥐', n: 'croissant' },
  { e: '🥯', n: 'bagel' },
  { e: '🍞', n: 'bread' },
  { e: '🥖', n: 'baguette' },
  { e: '🥨', n: 'pretzel' },
  { e: '🧀', n: 'cheese' },
  { e: '🥚', n: 'egg' },
  { e: '🍳', n: 'cooking egg' },
  { e: '🧈', n: 'butter' },
  { e: '🥞', n: 'pancakes' },
  { e: '🧇', n: 'waffle' },
  { e: '🥓', n: 'bacon' },
  { e: '🥩', n: 'cut of meat' },
  { e: '🍗', n: 'poultry leg' },
  { e: '🍖', n: 'meat on bone' },
  { e: '🦴', n: 'bone' },
  { e: '🌭', n: 'hot dog' },
  { e: '🍔', n: 'hamburger' },
  { e: '🍟', n: 'french fries' },
  { e: '🍕', n: 'pizza' },
  { e: '🥪', n: 'sandwich' },
  { e: '🥙', n: 'stuffed flatbread' },
  { e: '🧆', n: 'falafel' },
  { e: '🌮', n: 'taco' },
  { e: '🌯', n: 'burrito' },
  { e: '🫔', n: 'tamale' },
  { e: '🥗', n: 'green salad' },
  { e: '🥘', n: 'shallow pan of food' },
  { e: '🫕', n: 'fondue' },
  { e: '🍝', n: 'spaghetti' },
  { e: '🍜', n: 'steaming bowl ramen noodles' },
  { e: '🍲', n: 'pot of food' },
  { e: '🍛', n: 'curry rice' },
  { e: '🍣', n: 'sushi' },
  { e: '🍱', n: 'bento box' },
  { e: '🥟', n: 'dumpling' },
  { e: '🍤', n: 'fried shrimp' },
  { e: '🍙', n: 'rice ball' },
  { e: '🍚', n: 'cooked rice' },
  { e: '🍘', n: 'rice cracker' },
  { e: '🍥', n: 'fish cake' },
  { e: '🥠', n: 'fortune cookie' },
  { e: '🥮', n: 'moon cake' },
  { e: '🍢', n: 'oden' },
  { e: '🍡', n: 'dango' },
  { e: '🍧', n: 'shaved ice' },
  { e: '🍨', n: 'ice cream' },
  { e: '🍦', n: 'soft ice cream' },
  { e: '🥧', n: 'pie' },
  { e: '🧁', n: 'cupcake' },
  { e: '🍰', n: 'shortcake' },
  { e: '🎂', n: 'birthday cake' },
  { e: '🍮', n: 'custard flan' },
  { e: '🍭', n: 'lollipop' },
  { e: '🍬', n: 'candy' },
  { e: '🍫', n: 'chocolate bar' },
  { e: '🍿', n: 'popcorn' },
  { e: '🍩', n: 'doughnut donut' },
  { e: '🍪', n: 'cookie' },
  { e: '🌰', n: 'chestnut' },
  { e: '🥜', n: 'peanuts' },
  { e: '🍯', n: 'honey pot' },
  { e: '🥛', n: 'glass of milk' },
  { e: '🍼', n: 'baby bottle' },
  { e: '☕', n: 'hot beverage coffee' },
  { e: '🫖', n: 'teapot' },
  { e: '🍵', n: 'teacup' },
  { e: '🧋', n: 'bubble tea' },
  { e: '🧃', n: 'beverage box juice' },
  { e: '🥤', n: 'cup with straw' },
  { e: '🧉', n: 'mate' },
  { e: '🍶', n: 'sake' },
  { e: '🍾', n: 'champagne bottle' },
  { e: '🍷', n: 'wine glass' },
  { e: '🍸', n: 'cocktail' },
  { e: '🍹', n: 'tropical drink' },
  { e: '🍺', n: 'beer mug' },
  { e: '🍻', n: 'clinking beer mugs cheers' },
  { e: '🥂', n: 'clinking glasses cheers' },
  { e: '🥃', n: 'tumbler glass whiskey' },
  { e: '🧊', n: 'ice cube' },
];

const activities: EmojiEntry[] = [
  { e: '⚽', n: 'soccer ball football' },
  { e: '🏀', n: 'basketball' },
  { e: '🏈', n: 'american football' },
  { e: '⚾', n: 'baseball' },
  { e: '🥎', n: 'softball' },
  { e: '🎾', n: 'tennis' },
  { e: '🏐', n: 'volleyball' },
  { e: '🏉', n: 'rugby' },
  { e: '🎱', n: 'pool 8 ball' },
  { e: '🪀', n: 'yo yo' },
  { e: '🏓', n: 'ping pong table tennis' },
  { e: '🏸', n: 'badminton' },
  { e: '🏒', n: 'ice hockey' },
  { e: '🏑', n: 'field hockey' },
  { e: '🥍', n: 'lacrosse' },
  { e: '🏏', n: 'cricket' },
  { e: '🥅', n: 'goal net' },
  { e: '⛳', n: 'flag in hole golf' },
  { e: '🪁', n: 'kite' },
  { e: '🏹', n: 'bow and arrow' },
  { e: '🎣', n: 'fishing pole' },
  { e: '🤿', n: 'diving mask' },
  { e: '🥊', n: 'boxing glove' },
  { e: '🥋', n: 'martial arts uniform' },
  { e: '🎽', n: 'running shirt' },
  { e: '🛹', n: 'skateboard' },
  { e: '🛷', n: 'sled' },
  { e: '⛸️', n: 'ice skate' },
  { e: '🥌', n: 'curling stone' },
  { e: '🎿', n: 'skis' },
  { e: '⛷️', n: 'skier' },
  { e: '🏂', n: 'snowboarder' },
  { e: '🪂', n: 'parachute' },
  { e: '🏋️', n: 'person lifting weights' },
  { e: '🤼', n: 'people wrestling' },
  { e: '🤸', n: 'cartwheel' },
  { e: '⛹️', n: 'bouncing ball basketball' },
  { e: '🤺', n: 'fencer' },
  { e: '🤾', n: 'handball' },
  { e: '🏌️', n: 'golfer' },
  { e: '🏇', n: 'horse racing' },
  { e: '🧘', n: 'lotus position yoga' },
  { e: '🏄', n: 'surfer' },
  { e: '🏊', n: 'swimmer' },
  { e: '🤽', n: 'water polo' },
  { e: '🚣', n: 'rowboat' },
  { e: '🧗', n: 'climbing' },
  { e: '🚵', n: 'mountain bicyclist' },
  { e: '🚴', n: 'bicyclist' },
  { e: '🏆', n: 'trophy' },
  { e: '🥇', n: 'first place medal gold' },
  { e: '🥈', n: 'second place medal silver' },
  { e: '🥉', n: 'third place medal bronze' },
  { e: '🏅', n: 'sports medal' },
  { e: '🎖️', n: 'military medal' },
  { e: '🏵️', n: 'rosette' },
  { e: '🎗️', n: 'reminder ribbon' },
  { e: '🎫', n: 'ticket' },
  { e: '🎟️', n: 'admission tickets' },
  { e: '🎪', n: 'circus tent' },
  { e: '🤹', n: 'juggling' },
  { e: '🎭', n: 'performing arts' },
  { e: '🎨', n: 'artist palette' },
  { e: '🎬', n: 'clapper board movie' },
  { e: '🎤', n: 'microphone' },
  { e: '🎧', n: 'headphone' },
  { e: '🎼', n: 'musical score' },
  { e: '🎹', n: 'musical keyboard piano' },
  { e: '🥁', n: 'drum' },
  { e: '🪘', n: 'long drum' },
  { e: '🎷', n: 'saxophone' },
  { e: '🎺', n: 'trumpet' },
  { e: '🎸', n: 'guitar' },
  { e: '🪕', n: 'banjo' },
  { e: '🎻', n: 'violin' },
  { e: '🎲', n: 'dice game' },
  { e: '♟️', n: 'chess pawn' },
  { e: '🎯', n: 'bullseye dart' },
  { e: '🎳', n: 'bowling' },
  { e: '🎮', n: 'video game' },
  { e: '🎰', n: 'slot machine' },
  { e: '🧩', n: 'puzzle piece' },
];

const travel: EmojiEntry[] = [
  { e: '🚗', n: 'automobile car' },
  { e: '🚕', n: 'taxi' },
  { e: '🚙', n: 'sport utility vehicle suv' },
  { e: '🚌', n: 'bus' },
  { e: '🚎', n: 'trolleybus' },
  { e: '🏎️', n: 'racing car' },
  { e: '🚓', n: 'police car' },
  { e: '🚑', n: 'ambulance' },
  { e: '🚒', n: 'fire engine' },
  { e: '🚐', n: 'minibus' },
  { e: '🛻', n: 'pickup truck' },
  { e: '🚚', n: 'delivery truck' },
  { e: '🚛', n: 'articulated lorry' },
  { e: '🚜', n: 'tractor' },
  { e: '🛵', n: 'motor scooter' },
  { e: '🏍️', n: 'motorcycle' },
  { e: '🛺', n: 'auto rickshaw' },
  { e: '🚲', n: 'bicycle' },
  { e: '🛴', n: 'kick scooter' },
  { e: '🚁', n: 'helicopter' },
  { e: '✈️', n: 'airplane' },
  { e: '🛩️', n: 'small airplane' },
  { e: '🛫', n: 'airplane departure' },
  { e: '🛬', n: 'airplane arrival' },
  { e: '🪂', n: 'parachute' },
  { e: '⛵', n: 'sailboat' },
  { e: '🛶', n: 'canoe' },
  { e: '🚤', n: 'speedboat' },
  { e: '🛥️', n: 'motor boat' },
  { e: '🚢', n: 'ship' },
  { e: '🛳️', n: 'passenger ship' },
  { e: '⛴️', n: 'ferry' },
  { e: '🚀', n: 'rocket' },
  { e: '🛸', n: 'flying saucer ufo' },
  { e: '🚉', n: 'station' },
  { e: '🚊', n: 'tram' },
  { e: '🚝', n: 'monorail' },
  { e: '🚞', n: 'mountain railway' },
  { e: '🚋', n: 'tram car' },
  { e: '🚃', n: 'railway car' },
  { e: '🚂', n: 'locomotive' },
  { e: '🚆', n: 'train' },
  { e: '🚄', n: 'high speed train' },
  { e: '🚅', n: 'bullet train' },
  { e: '🚇', n: 'metro' },
  { e: '🚧', n: 'construction' },
  { e: '🚦', n: 'vertical traffic light' },
  { e: '🚥', n: 'horizontal traffic light' },
  { e: '🛑', n: 'stop sign' },
  { e: '🗺️', n: 'world map' },
  { e: '🗿', n: 'moai statue' },
  { e: '🗽', n: 'statue of liberty' },
  { e: '🗼', n: 'tokyo tower' },
  { e: '🏰', n: 'castle' },
  { e: '🏯', n: 'japanese castle' },
  { e: '🏟️', n: 'stadium' },
  { e: '🎡', n: 'ferris wheel' },
  { e: '🎢', n: 'roller coaster' },
  { e: '🎠', n: 'carousel horse' },
  { e: '⛲', n: 'fountain' },
  { e: '⛱️', n: 'umbrella on ground beach' },
  { e: '🏖️', n: 'beach with umbrella' },
  { e: '🏝️', n: 'desert island' },
  { e: '🏜️', n: 'desert' },
  { e: '🌋', n: 'volcano' },
  { e: '⛰️', n: 'mountain' },
  { e: '🏔️', n: 'snow capped mountain' },
  { e: '🗻', n: 'mount fuji' },
  { e: '🏕️', n: 'camping' },
  { e: '⛺', n: 'tent' },
  { e: '🏠', n: 'house' },
  { e: '🏡', n: 'house with garden' },
  { e: '🏘️', n: 'houses' },
  { e: '🏚️', n: 'derelict house' },
  { e: '🏗️', n: 'building construction' },
  { e: '🏢', n: 'office building' },
  { e: '🏭', n: 'factory' },
  { e: '🏬', n: 'department store' },
  { e: '🏣', n: 'japanese post office' },
  { e: '🏤', n: 'post office' },
  { e: '🏥', n: 'hospital' },
  { e: '🏦', n: 'bank' },
  { e: '🏨', n: 'hotel' },
  { e: '🏪', n: 'convenience store' },
  { e: '🏫', n: 'school' },
  { e: '🏩', n: 'love hotel' },
  { e: '💒', n: 'wedding' },
  { e: '⛪', n: 'church' },
  { e: '🕌', n: 'mosque' },
  { e: '🕍', n: 'synagogue' },
  { e: '🛕', n: 'hindu temple' },
  { e: '🕋', n: 'kaaba' },
  { e: '⛩️', n: 'shinto shrine' },
  { e: '🌅', n: 'sunrise' },
  { e: '🌄', n: 'sunrise over mountains' },
  { e: '🌇', n: 'sunset' },
  { e: '🌆', n: 'cityscape at dusk' },
  { e: '🌃', n: 'night with stars' },
  { e: '🌉', n: 'bridge at night' },
  { e: '🌌', n: 'milky way' },
  { e: '🎑', n: 'moon viewing ceremony' },
  { e: '🌍', n: 'globe europe africa' },
  { e: '🌎', n: 'globe americas' },
  { e: '🌏', n: 'globe asia australia' },
  { e: '🪐', n: 'ringed planet' },
];

const objects: EmojiEntry[] = [
  { e: '⌚', n: 'watch' },
  { e: '📱', n: 'mobile phone' },
  { e: '💻', n: 'laptop computer' },
  { e: '⌨️', n: 'keyboard' },
  { e: '🖥️', n: 'desktop computer' },
  { e: '🖨️', n: 'printer' },
  { e: '🖱️', n: 'computer mouse' },
  { e: '🖲️', n: 'trackball' },
  { e: '💽', n: 'computer disk' },
  { e: '💾', n: 'floppy disk save' },
  { e: '💿', n: 'optical disc cd' },
  { e: '📀', n: 'dvd' },
  { e: '🧮', n: 'abacus' },
  { e: '🎥', n: 'movie camera' },
  { e: '🎞️', n: 'film frames' },
  { e: '📽️', n: 'film projector' },
  { e: '📺', n: 'television' },
  { e: '📷', n: 'camera' },
  { e: '📸', n: 'camera with flash' },
  { e: '📹', n: 'video camera' },
  { e: '📼', n: 'videocassette' },
  { e: '🔍', n: 'magnifying glass tilted left search' },
  { e: '🔎', n: 'magnifying glass tilted right' },
  { e: '🕯️', n: 'candle' },
  { e: '💡', n: 'light bulb idea' },
  { e: '🔦', n: 'flashlight' },
  { e: '🏮', n: 'red paper lantern' },
  { e: '🪔', n: 'diya lamp' },
  { e: '📔', n: 'notebook with cover' },
  { e: '📕', n: 'closed book' },
  { e: '📖', n: 'open book' },
  { e: '📗', n: 'green book' },
  { e: '📘', n: 'blue book' },
  { e: '📙', n: 'orange book' },
  { e: '📚', n: 'books' },
  { e: '📓', n: 'notebook' },
  { e: '📒', n: 'ledger' },
  { e: '📃', n: 'page with curl' },
  { e: '📜', n: 'scroll' },
  { e: '📄', n: 'page facing up' },
  { e: '📰', n: 'newspaper' },
  { e: '🗞️', n: 'rolled newspaper' },
  { e: '📑', n: 'bookmark tabs' },
  { e: '🔖', n: 'bookmark' },
  { e: '🏷️', n: 'label tag' },
  { e: '💰', n: 'money bag' },
  { e: '🪙', n: 'coin' },
  { e: '💴', n: 'yen banknote' },
  { e: '💵', n: 'dollar banknote' },
  { e: '💶', n: 'euro banknote' },
  { e: '💷', n: 'pound banknote' },
  { e: '💸', n: 'money with wings' },
  { e: '💳', n: 'credit card' },
  { e: '🧾', n: 'receipt' },
  { e: '💎', n: 'gem stone diamond' },
  { e: '⚖️', n: 'balance scale' },
  { e: '🪜', n: 'ladder' },
  { e: '🧰', n: 'toolbox' },
  { e: '🪛', n: 'screwdriver' },
  { e: '🔧', n: 'wrench' },
  { e: '🔨', n: 'hammer' },
  { e: '⚒️', n: 'hammer and pick' },
  { e: '🛠️', n: 'hammer and wrench' },
  { e: '⛏️', n: 'pick' },
  { e: '🪚', n: 'carpentry saw' },
  { e: '🔩', n: 'nut and bolt' },
  { e: '⚙️', n: 'gear' },
  { e: '🪤', n: 'mouse trap' },
  { e: '🧱', n: 'brick' },
  { e: '⛓️', n: 'chains' },
  { e: '🧲', n: 'magnet' },
  { e: '🔫', n: 'water pistol gun' },
  { e: '💉', n: 'syringe' },
  { e: '🩸', n: 'drop of blood' },
  { e: '💊', n: 'pill' },
  { e: '🩹', n: 'adhesive bandage' },
  { e: '🩺', n: 'stethoscope' },
  { e: '🚪', n: 'door' },
  { e: '🛗', n: 'elevator' },
  { e: '🪞', n: 'mirror' },
  { e: '🪟', n: 'window' },
  { e: '🛏️', n: 'bed' },
  { e: '🛋️', n: 'couch and lamp' },
  { e: '🪑', n: 'chair' },
  { e: '🚽', n: 'toilet' },
  { e: '🪠', n: 'plunger' },
  { e: '🚿', n: 'shower' },
  { e: '🛁', n: 'bathtub' },
  { e: '🪒', n: 'razor' },
  { e: '🧴', n: 'lotion bottle' },
  { e: '🧷', n: 'safety pin' },
  { e: '🧹', n: 'broom' },
  { e: '🧺', n: 'basket' },
  { e: '🧻', n: 'roll of paper' },
  { e: '🧼', n: 'soap' },
  { e: '🫧', n: 'bubbles' },
  { e: '🧽', n: 'sponge' },
  { e: '🧯', n: 'fire extinguisher' },
  { e: '🛒', n: 'shopping cart' },
  { e: '🚬', n: 'cigarette' },
  { e: '⚰️', n: 'coffin' },
  { e: '🪦', n: 'headstone' },
  { e: '⚱️', n: 'funeral urn' },
  { e: '🎈', n: 'balloon' },
  { e: '🎏', n: 'carp streamer' },
  { e: '🎀', n: 'ribbon' },
  { e: '🎁', n: 'wrapped gift' },
  { e: '🎊', n: 'confetti ball' },
  { e: '🎉', n: 'party popper celebration' },
  { e: '🎎', n: 'japanese dolls' },
  { e: '🎐', n: 'wind chime' },
  { e: '🎌', n: 'crossed flags' },
  { e: '🏮', n: 'red paper lantern' },
  { e: '🧧', n: 'red envelope' },
  { e: '✉️', n: 'envelope' },
  { e: '📧', n: 'email' },
  { e: '📨', n: 'incoming envelope' },
  { e: '📩', n: 'envelope with arrow' },
  { e: '📤', n: 'outbox tray' },
  { e: '📥', n: 'inbox tray' },
  { e: '📦', n: 'package' },
  { e: '📫', n: 'closed mailbox flag up' },
  { e: '📪', n: 'closed mailbox flag down' },
  { e: '📬', n: 'open mailbox flag up' },
  { e: '📭', n: 'open mailbox flag down' },
  { e: '📮', n: 'postbox' },
  { e: '🗳️', n: 'ballot box' },
  { e: '✏️', n: 'pencil' },
  { e: '✒️', n: 'black nib pen' },
  { e: '🖋️', n: 'fountain pen' },
  { e: '🖊️', n: 'pen' },
  { e: '🖌️', n: 'paintbrush' },
  { e: '🖍️', n: 'crayon' },
  { e: '📝', n: 'memo writing' },
  { e: '💼', n: 'briefcase' },
  { e: '📁', n: 'file folder' },
  { e: '📂', n: 'open file folder' },
  { e: '🗂️', n: 'card index dividers' },
  { e: '📅', n: 'calendar' },
  { e: '📆', n: 'tear off calendar' },
  { e: '🗒️', n: 'spiral notepad' },
  { e: '🗓️', n: 'spiral calendar' },
  { e: '📇', n: 'card index' },
  { e: '📈', n: 'chart increasing' },
  { e: '📉', n: 'chart decreasing' },
  { e: '📊', n: 'bar chart' },
  { e: '📋', n: 'clipboard' },
  { e: '📌', n: 'pushpin' },
  { e: '📍', n: 'round pushpin' },
  { e: '📎', n: 'paperclip' },
  { e: '🖇️', n: 'linked paperclips' },
  { e: '📏', n: 'straight ruler' },
  { e: '📐', n: 'triangular ruler' },
  { e: '✂️', n: 'scissors' },
  { e: '🗃️', n: 'card file box' },
  { e: '🗄️', n: 'file cabinet' },
  { e: '🗑️', n: 'wastebasket trash' },
  { e: '🔒', n: 'locked' },
  { e: '🔓', n: 'unlocked' },
  { e: '🔏', n: 'locked with pen' },
  { e: '🔐', n: 'locked with key' },
  { e: '🔑', n: 'key' },
  { e: '🗝️', n: 'old key' },
];

const symbols: EmojiEntry[] = [
  { e: '⭐', n: 'star' },
  { e: '🌟', n: 'glowing star' },
  { e: '✨', n: 'sparkles' },
  { e: '⚡', n: 'high voltage lightning' },
  { e: '🔥', n: 'fire flame' },
  { e: '☀️', n: 'sun' },
  { e: '🌤️', n: 'sun behind small cloud' },
  { e: '⛅', n: 'sun behind cloud' },
  { e: '🌥️', n: 'sun behind large cloud' },
  { e: '🌦️', n: 'sun behind rain cloud' },
  { e: '☁️', n: 'cloud' },
  { e: '🌧️', n: 'cloud with rain' },
  { e: '⛈️', n: 'cloud lightning rain' },
  { e: '🌩️', n: 'cloud with lightning' },
  { e: '🌨️', n: 'cloud with snow' },
  { e: '❄️', n: 'snowflake' },
  { e: '☃️', n: 'snowman' },
  { e: '⛄', n: 'snowman without snow' },
  { e: '🌬️', n: 'wind face' },
  { e: '🌪️', n: 'tornado' },
  { e: '🌫️', n: 'fog' },
  { e: '🌈', n: 'rainbow' },
  { e: '☔', n: 'umbrella with rain' },
  { e: '☂️', n: 'umbrella' },
  { e: '💧', n: 'droplet' },
  { e: '🌊', n: 'water wave' },
  { e: '🌑', n: 'new moon' },
  { e: '🌒', n: 'waxing crescent moon' },
  { e: '🌓', n: 'first quarter moon' },
  { e: '🌔', n: 'waxing gibbous moon' },
  { e: '🌕', n: 'full moon' },
  { e: '🌖', n: 'waning gibbous moon' },
  { e: '🌗', n: 'last quarter moon' },
  { e: '🌘', n: 'waning crescent moon' },
  { e: '🌙', n: 'crescent moon' },
  { e: '🌚', n: 'new moon face' },
  { e: '🌛', n: 'first quarter moon face' },
  { e: '🌜', n: 'last quarter moon face' },
  { e: '🌡️', n: 'thermometer' },
  { e: '☄️', n: 'comet' },
  { e: '⏰', n: 'alarm clock' },
  { e: '⏱️', n: 'stopwatch' },
  { e: '⏲️', n: 'timer clock' },
  { e: '🕰️', n: 'mantelpiece clock' },
  { e: '⌛', n: 'hourglass done' },
  { e: '⏳', n: 'hourglass not done' },
  { e: '🆗', n: 'ok button' },
  { e: '🆕', n: 'new button' },
  { e: '🆒', n: 'cool button' },
  { e: '🆓', n: 'free button' },
  { e: '🆙', n: 'up button' },
  { e: '🆖', n: 'ng button' },
  { e: '🆔', n: 'id button' },
  { e: '🆚', n: 'vs button' },
  { e: '🆎', n: 'ab blood' },
  { e: '🅰️', n: 'a blood' },
  { e: '🅱️', n: 'b blood' },
  { e: '🅾️', n: 'o blood' },
  { e: '🆑', n: 'cl button' },
  { e: '🅿️', n: 'p parking' },
  { e: '🚫', n: 'prohibited no' },
  { e: '⛔', n: 'no entry' },
  { e: '✅', n: 'check mark button green' },
  { e: '❌', n: 'cross mark x' },
  { e: '❎', n: 'cross mark button' },
  { e: '✔️', n: 'check mark' },
  { e: '☑️', n: 'check box check' },
  { e: '➕', n: 'plus' },
  { e: '➖', n: 'minus' },
  { e: '➗', n: 'divide' },
  { e: '✖️', n: 'multiply' },
  { e: '♾️', n: 'infinity' },
  { e: '‼️', n: 'double exclamation' },
  { e: '⁉️', n: 'exclamation question' },
  { e: '❓', n: 'red question mark' },
  { e: '❔', n: 'white question mark' },
  { e: '❗', n: 'red exclamation mark' },
  { e: '❕', n: 'white exclamation mark' },
  { e: '〽️', n: 'part alternation mark' },
  { e: '©️', n: 'copyright' },
  { e: '®️', n: 'registered' },
  { e: '™️', n: 'trade mark' },
  { e: '🔠', n: 'input latin uppercase' },
  { e: '🔡', n: 'input latin lowercase' },
  { e: '🔢', n: 'input numbers' },
  { e: '🔣', n: 'input symbols' },
  { e: '🔤', n: 'input latin letters' },
  { e: '🔥', n: 'fire' },
  { e: '⚜️', n: 'fleur de lis' },
  { e: '🔱', n: 'trident' },
  { e: '⚛️', n: 'atom symbol' },
  { e: '🕉️', n: 'om' },
  { e: '✡️', n: 'star of david' },
  { e: '☸️', n: 'wheel of dharma' },
  { e: '☯️', n: 'yin yang' },
  { e: '✝️', n: 'latin cross' },
  { e: '☦️', n: 'orthodox cross' },
  { e: '☪️', n: 'star and crescent' },
  { e: '☮️', n: 'peace symbol' },
  { e: '🕎', n: 'menorah' },
  { e: '🔯', n: 'dotted six pointed star' },
  { e: '♈', n: 'aries' },
  { e: '♉', n: 'taurus' },
  { e: '♊', n: 'gemini' },
  { e: '♋', n: 'cancer' },
  { e: '♌', n: 'leo' },
  { e: '♍', n: 'virgo' },
  { e: '♎', n: 'libra' },
  { e: '♏', n: 'scorpio' },
  { e: '♐', n: 'sagittarius' },
  { e: '♑', n: 'capricorn' },
  { e: '♒', n: 'aquarius' },
  { e: '♓', n: 'pisces' },
  { e: '⛎', n: 'ophiuchus' },
  { e: '🔀', n: 'shuffle' },
  { e: '🔁', n: 'repeat' },
  { e: '🔂', n: 'repeat single' },
  { e: '▶️', n: 'play' },
  { e: '⏩', n: 'fast forward' },
  { e: '⏭️', n: 'next track' },
  { e: '⏯️', n: 'play pause' },
  { e: '◀️', n: 'reverse' },
  { e: '⏪', n: 'fast reverse' },
  { e: '⏮️', n: 'last track' },
  { e: '🔼', n: 'upwards button' },
  { e: '⏫', n: 'fast up' },
  { e: '🔽', n: 'downwards button' },
  { e: '⏬', n: 'fast down' },
  { e: '⏸️', n: 'pause' },
  { e: '⏹️', n: 'stop' },
  { e: '⏺️', n: 'record' },
  { e: '⏏️', n: 'eject' },
  { e: '🎦', n: 'cinema' },
  { e: '🔅', n: 'dim button' },
  { e: '🔆', n: 'bright button' },
  { e: '📶', n: 'antenna bars signal' },
  { e: '📳', n: 'vibration mode' },
  { e: '📴', n: 'mobile phone off' },
  { e: '♀️', n: 'female sign' },
  { e: '♂️', n: 'male sign' },
  { e: '⚧️', n: 'transgender symbol' },
  { e: '⚕️', n: 'medical symbol' },
  { e: '♻️', n: 'recycling symbol' },
  { e: '⚜️', n: 'fleur de lis' },
  { e: '🔰', n: 'japanese symbol for beginner' },
  { e: '🔺', n: 'red triangle pointed up' },
  { e: '🔻', n: 'red triangle pointed down' },
  { e: '🔸', n: 'small orange diamond' },
  { e: '🔹', n: 'small blue diamond' },
  { e: '🔶', n: 'large orange diamond' },
  { e: '🔷', n: 'large blue diamond' },
  { e: '🔳', n: 'white square button' },
  { e: '🔲', n: 'black square button' },
  { e: '▪️', n: 'black small square' },
  { e: '▫️', n: 'white small square' },
  { e: '◾', n: 'black medium small square' },
  { e: '◽', n: 'white medium small square' },
  { e: '◼️', n: 'black medium square' },
  { e: '◻️', n: 'white medium square' },
  { e: '⬛', n: 'black large square' },
  { e: '⬜', n: 'white large square' },
  { e: '🟥', n: 'red square' },
  { e: '🟧', n: 'orange square' },
  { e: '🟨', n: 'yellow square' },
  { e: '🟩', n: 'green square' },
  { e: '🟦', n: 'blue square' },
  { e: '🟪', n: 'purple square' },
  { e: '🟫', n: 'brown square' },
  { e: '🔴', n: 'red circle' },
  { e: '🟠', n: 'orange circle' },
  { e: '🟡', n: 'yellow circle' },
  { e: '🟢', n: 'green circle' },
  { e: '🔵', n: 'blue circle' },
  { e: '🟣', n: 'purple circle' },
  { e: '🟤', n: 'brown circle' },
  { e: '⚫', n: 'black circle' },
  { e: '⚪', n: 'white circle' },
];

const flags: EmojiEntry[] = [
  { e: '🏁', n: 'chequered flag' },
  { e: '🚩', n: 'triangular flag' },
  { e: '🎌', n: 'crossed flags' },
  { e: '🏴', n: 'black flag' },
  { e: '🏳️', n: 'white flag' },
  { e: '🏳️‍🌈', n: 'rainbow flag pride' },
  { e: '🏳️‍⚧️', n: 'transgender flag' },
  { e: '🏴‍☠️', n: 'pirate flag' },
  { e: '🇺🇸', n: 'flag united states usa' },
  { e: '🇬🇧', n: 'flag united kingdom uk' },
  { e: '🇨🇦', n: 'flag canada' },
  { e: '🇩🇪', n: 'flag germany' },
  { e: '🇫🇷', n: 'flag france' },
  { e: '🇪🇸', n: 'flag spain' },
  { e: '🇮🇹', n: 'flag italy' },
  { e: '🇯🇵', n: 'flag japan' },
  { e: '🇰🇷', n: 'flag south korea' },
  { e: '🇨🇳', n: 'flag china' },
  { e: '🇮🇳', n: 'flag india' },
  { e: '🇧🇷', n: 'flag brazil' },
  { e: '🇲🇽', n: 'flag mexico' },
  { e: '🇦🇺', n: 'flag australia' },
  { e: '🇳🇿', n: 'flag new zealand' },
  { e: '🇳🇱', n: 'flag netherlands' },
  { e: '🇧🇪', n: 'flag belgium' },
  { e: '🇸🇪', n: 'flag sweden' },
  { e: '🇳🇴', n: 'flag norway' },
  { e: '🇩🇰', n: 'flag denmark' },
  { e: '🇫🇮', n: 'flag finland' },
  { e: '🇮🇪', n: 'flag ireland' },
  { e: '🇵🇹', n: 'flag portugal' },
  { e: '🇨🇭', n: 'flag switzerland' },
  { e: '🇦🇹', n: 'flag austria' },
  { e: '🇬🇷', n: 'flag greece' },
  { e: '🇵🇱', n: 'flag poland' },
  { e: '🇨🇿', n: 'flag czechia' },
  { e: '🇷🇺', n: 'flag russia' },
  { e: '🇺🇦', n: 'flag ukraine' },
  { e: '🇹🇷', n: 'flag turkey' },
  { e: '🇮🇱', n: 'flag israel' },
  { e: '🇸🇦', n: 'flag saudi arabia' },
  { e: '🇦🇪', n: 'flag uae' },
  { e: '🇿🇦', n: 'flag south africa' },
  { e: '🇪🇬', n: 'flag egypt' },
  { e: '🇳🇬', n: 'flag nigeria' },
  { e: '🇰🇪', n: 'flag kenya' },
  { e: '🇦🇷', n: 'flag argentina' },
  { e: '🇨🇱', n: 'flag chile' },
  { e: '🇨🇴', n: 'flag colombia' },
  { e: '🇵🇪', n: 'flag peru' },
  { e: '🇻🇪', n: 'flag venezuela' },
  { e: '🇹🇭', n: 'flag thailand' },
  { e: '🇻🇳', n: 'flag vietnam' },
  { e: '🇵🇭', n: 'flag philippines' },
  { e: '🇮🇩', n: 'flag indonesia' },
  { e: '🇲🇾', n: 'flag malaysia' },
  { e: '🇸🇬', n: 'flag singapore' },
  { e: '🇭🇰', n: 'flag hong kong' },
  { e: '🇹🇼', n: 'flag taiwan' },
];

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  { id: 'smileys', label: 'Smileys', icon: '😀', items: smileys },
  { id: 'gestures', label: 'People & Body', icon: '👋', items: gestures },
  { id: 'hearts', label: 'Hearts & Symbols', icon: '❤️', items: hearts },
  { id: 'animals', label: 'Animals & Nature', icon: '🐶', items: animals },
  { id: 'food', label: 'Food & Drink', icon: '🍔', items: food },
  { id: 'activities', label: 'Activities', icon: '⚽', items: activities },
  { id: 'travel', label: 'Travel & Places', icon: '🚗', items: travel },
  { id: 'objects', label: 'Objects', icon: '💡', items: objects },
  { id: 'symbols', label: 'Symbols', icon: '✨', items: symbols },
  { id: 'flags', label: 'Flags', icon: '🏳️', items: flags },
];

const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.items);

export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const tokens = q.split(/\s+/).filter(Boolean);
  return ALL_EMOJIS.filter((entry) => tokens.every((t) => entry.n.includes(t)));
}
